name: Metrics
on:
  # Daily Updates
  schedule: [{cron: "0 0 * * *"}]
  # Manually Run
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
