name: Metrics
on:
  # Daily Updates
  schedule: [{cron: "0 0 * * *"}]
  # Manually Run
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: isocal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: addyire
          template: classic
          base: ""
          config_timezone: America/New_York
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
      - uses: lowlighter/metrics@latest
        with:
          filename: isocal.svg  
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{secrets.SPOTIFY_CLIENT_ID}}, ${{secrets.SPOTIFY_CLIENT_SECRET}}, ${{secrets.SPOTIFY_REFRESH_TOKEN}}"
          plugin_music_mode: recent
          plugin_music_limit: 3
          plugin_music_time_range: short
          plugin_music_top_type: tracks
      - uses: lowlighter/metrics@latest
        with:
          filename: isocal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: addyire
          template: classic
          base: ""
          config_timezone: America/New_York
          plugin_lines: yes
          plugin_lines_sections: history
